language: cpp
dist: bionic
compiler: gcc
<<<<<<< HEAD
dist: bionic

install: 
  - sudo apt update -qq
  # R
  - sudo apt-get install r-base r-base-dev
=======

install: 
  - sudo apt update -qq
>>>>>>> develop

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_r
